services:

  web:
    build:
      context: ./packages/front-end
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./packages/front-end:/www
      - ./.env:/www/.env:ro
      - /www/node_modules
    networks:
      - nuxt

  api:
    build:
      context: ./packages/back-end
    ports:
      - 8080:8080
    volumes:
      - ./packages/back-end:/www
    networks:
      - laravel
      - nuxt
    depends_on:
      api-db:
        condition: service_healthy
  api-db:
    image: mysql:latest
    expose:
      - 3306
    networks:
      - laravel
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

networks:
  laravel:
  nuxt: